Repository open-telemetry/semantic-conventions, pull requests merged in 2023-11, with the labels that each got.

#21 Add Semantic conventions for TLS/SSL encrypted communication
  CHANGELOG.md
  docs/attributes-registry/README.md
  docs/attributes-registry/tls.md
  model/registry/tls.yaml
Labels: experts needed

#537 [backport to 1.23.x] Temp fix for separation of resource and semantic attributes (#524)
  model/registry/cloud.yaml
  model/registry/container.yaml
  model/registry/oci.yaml
Labels: bug

#558 Improve visibility of used spec version in the semconv repo
  CONTRIBUTING.md
  README.md
  internal/tools/update_specification_version.sh
Labels: editorial
