Repository open-telemetry/semantic-conventions, pull requests merged in 2023-10, with the labels that each got.

#366 Improve HTTP metric briefs
  CHANGELOG.md
  docs/http/http-metrics.md
  model/metrics/http.yaml
Labels: editorial

#398 Change `network.protocol.name` from recommended to opt-in in the HTTP semconv
  CHANGELOG.md
  docs/http/http-metrics.md
  docs/http/http-spans.md
  model/http-common.yaml
Labels: ready-to-merge

#67 added mobile instrumentation to log-event semantic conventions
  docs/mobile/README.md
  docs/mobile/events.md
  model/logs/mobile-events.yaml
Labels: experts needed

#447 Remove outdated section in rpc-metrics.md that no longer applies
  docs/rpc/rpc-metrics.md
Labels: editorial
