Repository open-telemetry/semantic-conventions, pull requests merged in 2024-07, with the labels that each got.

#1207 Bump weaver to latest version.
  Makefile
Labels: Skip Changelog

#1200 GenAI: Rename prompt and completion tokens attributes to input and output
  .chloggen/1200.yaml
  docs/attributes-registry/gen-ai.md
  docs/gen-ai/gen-ai-spans.md
  model/registry/deprecated/gen-ai.yaml
  model/registry/gen-ai.yaml
  model/trace/gen-ai.yaml
  schema-next.yaml
Labels: area:gen-ai

#1233 Editorial: mention that Redis `db.namespace` is a string
  docs/database/redis.md
  model/trace/database.yaml
Labels: Skip Changelog

#1182 CloudEvents should re-use existing HTTP or messaging conventions
  .chloggen/cloud-events-restructure.yaml
  docs/cloudevents/cloudevents-spans.md
Labels: area:cloudevents

#1260 Add semconv-event-approvers to CODEOWNERS
  .github/CODEOWNERS
Labels: Skip Changelog

#1208 Add policy enforcement for attribute registry.
  Makefile
  policies/registry.rego
Labels: Skip Changelog

#1271 (chore): bump to latest weaver version.
  Makefile
Labels: Skip Changelog

#1284 [editorial] Move supplementary-guidelines into docs
  docs/README.md
  docs/cloud-providers/aws-sdk.md
  docs/faas/aws-lambda.md
  docs/general/attributes.md
  docs/general/events.md
  docs/general/logs.md
  docs/general/metrics.md
  docs/non-normative/README.md
  docs/non-normative/compatibility/README.md
  docs/non-normative/compatibility/aws.md
  docs/non-normative/http-migration.md
  docs/non-normative/libraries.md
  internal/tools/update_specification_version.sh
Labels: Skip Changelog

#1286 Add editorconfig for yaml, rego and makefile, fix rego tabs
  .editorconfig
  policies/registry.rego
Labels: Skip Changelog

#1209 Add attribute name and const names checks
  .github/workflows/checks.yml
  Makefile
  policies/attribute_name_collisions.rego
  policies/registry.rego
Labels: Skip Changelog
