Repository open-telemetry/semantic-conventions, pull requests merged in 2024-12, with the labels that each got.

#1642 Relax collision detection policy to allow collisions between deprecated namespaces and attributes (and vice-versa)
  policies/attribute_name_collisions.rego
  policies_test/attribute_name_collisions_test.rego
Labels: Skip Changelog

#1630 Include PR/Issue links in the changelog
  .chloggen/CHANGELOG.tmpl
  .chloggen/config.yaml
Labels: tooling, Skip Changelog

#1643 Update approvers
  README.md
Labels: Skip Changelog

#1597 add k8s semconv migration non-normative doc
  .chloggen/k8s-migration.yaml
  .github/CODEOWNERS
  docs/non-normative/k8s-migration.md
Labels: area:k8s

#1654 Update weaver and add missing stability levels to spans, resources and events
  .vscode/settings.json
  dependencies.Dockerfile
  model/android/resources.yaml
  model/aws/ecs-resources.yaml
  model/aws/eks-resources.yaml
  model/aws/lambda-spans.yaml
  model/aws/logs-resources.yaml
  model/aws/sdk-spans.yml
  model/browser/resources.yaml
  model/cloud/resources.yaml
  model/cloudfoundry/resources.yaml
  model/container/resources.yaml
  model/database/spans.yaml
  model/deployment/resources.yaml
  model/device/resources.yaml
  model/faas/resources.yaml
  model/faas/spans.yaml
  model/feature-flags/logs.yaml
  model/gcp/cloud-run-resources.yaml
  model/gcp/gce-resources.yaml
  model/graphql/spans.yml
  model/heroku/resources.yaml
  model/host/resources.yaml
  model/k8s/resources.yaml
  model/os/resources.yaml
  model/otel/resources.yaml
  model/process/resources.yaml
  model/rpc/spans.yaml
  model/webengine/resources.yaml
Labels: Skip Changelog

#1652 Add code owners for the http and db migration guides
  .github/CODEOWNERS
Labels: Skip Changelog

#903 add new namespace “security_rule.*"
  .chloggen/rule_new.yaml
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/change_proposal.yaml
  .github/ISSUE_TEMPLATE/new-conventions.yaml
  docs/attributes-registry/README.md
  docs/attributes-registry/security-rule.md
  model/security-rule/registry.yaml
Labels: never stale, area:security

#1664 Change `<PID>` to `[PID]`
  docs/attributes-registry/process.md
  docs/resource/process.md
  model/process/registry.yaml
Labels: Skip Changelog

#1665 Update weaver to version 0.12.0
  .vscode/settings.json
  dependencies.Dockerfile
  model/profile/registry.yaml
Labels: Skip Changelog

#1674 added missing display names to some registry groups
  docs/attributes-registry/azure.md
  docs/attributes-registry/cicd.md
  model/artifact/registry.yaml
  model/azure/registry.yaml
  model/cicd/registry.yaml
  model/cloudfoundry/registry.yaml
  model/hardware/registry.yaml
  model/linux/registry.yaml
  model/profile/registry.yaml
  model/test/registry.yaml
  model/vcs/registry.yaml
Labels: Skip Changelog

#1469 GenAI events - yamlify body definitions and cosmetic examples improvements
  .chloggen/1469.yaml
  docs/gen-ai/gen-ai-events.md
  model/gen-ai/events.yaml
  templates/registry/markdown/body_field_table.j2
Labels: area:gen-ai

#1635 Messaging: Clarify `{destination}` value used on span name
  .chloggen/clarify-temporary-destination.yaml
  docs/messaging/messaging-spans.md
Labels: area:messaging

#1679 Ignore sporadically failing link
  .markdown_link_check_config.json
Labels: Skip Changelog

#1682 Update links to openmetrics to reference the v1.0.0 release
  docs/hardware/common.md
  model/hardware/common-metrics.yaml
Labels: Skip Changelog

#1636 Add metrics for deployment, replicaset, replication_controller, statefulset and hpa
  .chloggen/add_deploy_replica_metrics.yaml
  docs/non-normative/k8s-migration.md
  docs/system/k8s-metrics.md
  model/k8s/metrics.yaml
Labels: area:k8s

#1649 Add k8s daemonset metrics
  .chloggen/add_ds_metrics.yaml
  docs/non-normative/k8s-migration.md
  docs/system/k8s-metrics.md
  model/k8s/metrics.yaml
Labels: area:k8s

#1702 Improve rendering of database release candidate status
  docs/attributes-registry/db.md
  docs/database/cassandra.md
  docs/database/cosmosdb.md
  docs/database/couchdb.md
  docs/database/database-metrics.md
  docs/database/database-spans.md
  docs/database/elasticsearch.md
  docs/database/hbase.md
  docs/database/mariadb.md
  docs/database/mongodb.md
  docs/database/mssql.md
  docs/database/mysql.md
  docs/database/postgresql.md
  docs/database/redis.md
  docs/database/sql.md
  model/database/metrics.yaml
  model/database/registry.yaml
  templates/registry/markdown/stability.j2
Labels: Skip Changelog

#1705 Document which conventions belong in this repo
  CONTRIBUTING.md
Labels: Skip Changelog

#1704 [editorial] A few random doc fixes
  CONTRIBUTING.md
  Makefile
  docs/attributes-registry/README.md
  docs/attributes-registry/db.md
  docs/attributes-registry/dns.md
  docs/gen-ai/gen-ai-events.md
  docs/general/semantic-convention-groups.md
  model/README.md
  templates/registry/markdown/readme.md.j2
  templates/registry/markdown/weaver.yaml
Labels: Skip Changelog
