Repository open-telemetry/semantic-conventions, pull requests merged in 2024-03, with the labels that each got.

#788 [chore] Add recommendation for lowercase attribute names
  docs/general/attribute-naming.md
Labels: editorial

#787 [chore] Improve check/fix make targets
  .prettierignore
  CONTRIBUTING.md
  Makefile
  docs/cloudevents/cloudevents-spans.md
  docs/database/database-metrics.md
  docs/database/database-spans.md
  docs/dotnet/dotnet-aspnetcore-metrics.md
  docs/dotnet/dotnet-dns-metrics.md
  docs/dotnet/dotnet-http-metrics.md
  docs/exceptions/exceptions-logs.md
  docs/exceptions/exceptions-spans.md
  docs/faas/aws-lambda.md
  docs/faas/faas-metrics.md
  docs/faas/faas-spans.md
  docs/general/attributes.md
  docs/general/logs.md
  docs/general/metrics.md
  docs/http/http-metrics.md
  docs/http/http-spans.md
  docs/messaging/kafka.md
  docs/messaging/messaging-metrics.md
  docs/messaging/messaging-spans.md
  docs/mobile/events.md
  docs/resource/README.md
  docs/resource/process.md
  docs/rpc/rpc-metrics.md
  docs/rpc/rpc-spans.md
  docs/runtime/README.md
  docs/runtime/jvm-metrics.md
  docs/system/hardware-metrics.md
  docs/system/process-metrics.md
  docs/system/system-metrics.md
Labels: editorial, tooling

#544 moving android to the registry attributes
  docs/attributes-registry/README.md
  docs/attributes-registry/android.md
  docs/resource/android.md
  model/registry/android.yaml
  model/resource/android.yaml
Labels: Skip Changelog

#525 move faas to registry
  docs/attributes-registry/README.md
  docs/attributes-registry/faas.md
  docs/faas/faas-metrics.md
  docs/faas/faas-spans.md
  docs/resource/faas.md
  model/faas-common.yaml
  model/registry/faas.yaml
  model/resource/faas.yaml
  model/trace/faas.yaml
Labels: Skip Changelog

#777 Add Issue templates and automation scripts
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/change_proposal.yaml
  .github/ISSUE_TEMPLATE/new-conventions.yaml
  .github/workflows/checks.yml
  .github/workflows/generate-registry-area-labels.yml
  .github/workflows/prepare-new-issue.yml
  .github/workflows/scripts/generate-registry-area-labels.sh
  .github/workflows/scripts/get-registry-areas.sh
  .github/workflows/scripts/prepare-new-issue.sh
  .yamllint
  Makefile
  internal/tools/scripts/update-issue-template-areas.sh
Labels: Skip Changelog

#846 Fix path of yaml files for VSCode schema auto completion
  .vscode/settings.json
Labels: Skip Changelog
