Repository open-telemetry/semantic-conventions, pull requests merged in 2024-05, with the labels that each got.

#1005 Add registry md check and fix violations
  .github/workflows/checks.yml
  docs/attributes-registry/messaging.md
Labels: Skip Changelog

#1010 Update markdownlint version and fix violation
  .markdownlint.yaml
  docs/messaging/kafka.md
  package.json
Labels: Skip Changelog

#1015 [chore] Fix typo
  .markdown_link_check_config.json
Labels: Skip Changelog

#1021 Fix CI: regenerate semconv with latest weaver
  Makefile
  docs/object-stores/s3.md
  docs/resource/k8s.md
Labels: Skip Changelog

#1046 [chore] Move last 'loose' attribute to registry.
  docs/attributes-registry/jvm.md
  model/metrics/jvm-metrics-experimental.yaml
  model/registry/jvm.yaml
Labels: Skip Changelog

#1060 [chore] Fix typos
  CHANGELOG.md
  Makefile
  docs/attributes-registry/cloud.md
  docs/faas/faas-spans.md
  docs/general/metrics.md
  docs/general/trace.md
  docs/resource/cloud.md
  docs/resource/faas.md
  internal/tools/schema_check.sh
  model/metrics/system-metrics.yaml
  model/registry/cloud.yaml
  model/registry/system.yaml
Labels: editorial

#1065 [chore] Fix links to Opt-In in container-metrics.md
  docs/system/container-metrics.md
Labels: editorial

#955 LLM common metrics for Generative AI
  .chloggen/811.yaml
  docs/attributes-registry/gen-ai.md
  docs/gen-ai/README.md
  docs/gen-ai/gen-ai-metrics.md
  model/metrics/gen-ai.yaml
  model/registry/gen-ai.yaml
Labels: area:gen-ai
