Repository open-telemetry/semantic-conventions, pull requests merged in 2024-02, with the labels that each got.

#572 Define additional Azure messaging attributes
  CHANGELOG.md
  docs/attributes-registry/messaging.md
  docs/messaging/azure-messaging.md
  docs/messaging/messaging-metrics.md
  docs/messaging/messaging-spans.md
  model/registry/messaging.yaml
  model/trace/messaging.yaml
Labels: Stale

#637 Use `chloggen` go tool for managing the changelog
  .chloggen/TEMPLATE.yaml
  .chloggen/config.yaml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/changelog.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
Labels: tooling, Skip Changelog

#685 Chore: Bump stale bot version and exclude certain cases
  .github/workflows/stale-pr.yml
Labels: Skip Changelog

#684 Fix header level in README.md
  docs/resource/README.md
Labels: editorial, Skip Changelog

#691 A few small documentation things around changelog generation.
  .chloggen/TEMPLATE.yaml
  CONTRIBUTING.md
Labels: Skip Changelog

#683 Fix jvm buffer metric schema translations
  CHANGELOG.md
  schema-next.yaml
Labels: Skip Changelog

#688 [editorial] Fix path base in Hugo front matter
  docs/README.md
  docs/attributes-registry/host.md
  docs/attributes-registry/os.md
  docs/attributes-registry/url.md
  docs/cloud-providers/README.md
  docs/cloudevents/README.md
  docs/database/README.md
  docs/dotnet/README.md
  docs/exceptions/README.md
  docs/faas/README.md
  docs/feature-flags/README.md
  docs/general/README.md
  docs/http/README.md
  docs/messaging/README.md
  docs/mobile/README.md
  docs/object-stores/README.md
  docs/resource/README.md
  docs/resource/cloud-provider/README.md
  docs/resource/cloud-provider/aws/README.md
  docs/resource/cloud-provider/gcp/README.md
  docs/rpc/README.md
  docs/system/README.md
  docs/url/README.md
Labels: Skip Changelog

#733 Add placeholder for database stability transition plan
  docs/database/README.md
  docs/database/database-metrics.md
  docs/database/database-spans.md
Labels: Skip Changelog

#734 Add placeholder for messaging stabiblity transition plan
  docs/messaging/messaging-metrics.md
  docs/messaging/messaging-spans.md
Labels: Skip Changelog

#741 [chore] Change Traces SemConv Status to Mixed
  docs/general/trace.md
Labels: Skip Changelog

#745 [chore] Exclude issues from stale bot check
  .github/workflows/stale-pr.yml
Labels: bug

#776 Add Liudmila to semconv maintainers.
  README.md
Labels: Skip Changelog

#779 Double backslash -> Single backslash
  docs/resource/host.md
Labels: editorial, Skip Changelog

#783 [chore] URL attributes: consistently use code font for URLs and URL parts
  docs/attributes-registry/url.md
  model/registry/url.yaml
Labels: editorial, Skip Changelog
