Repository open-telemetry/semantic-conventions, pull requests merged in 2024-08, with the labels that each got.

#1305 Fix broken CI checks (community links and newly added prefixes)
  .github/CODEOWNERS
  CONTRIBUTING.md
  README.md
  model/registry/azure.yaml
Labels: Skip Changelog

#1306 Update spec version to 1.35.0
  CONTRIBUTING.md
  README.md
  docs/database/database-metrics.md
  docs/database/database-spans.md
  docs/dns/dns-metrics.md
  docs/dotnet/dotnet-aspnetcore-metrics.md
  docs/dotnet/dotnet-dns-metrics.md
  docs/dotnet/dotnet-http-metrics.md
  docs/dotnet/dotnet-kestrel-metrics.md
  docs/dotnet/dotnet-signalr-metrics.md
  docs/exceptions/exceptions-logs.md
  docs/exceptions/exceptions-spans.md
  docs/faas/aws-lambda.md
  docs/faas/faas-metrics.md
  docs/feature-flags/feature-flags-logs.md
  docs/gen-ai/gen-ai-metrics.md
  docs/gen-ai/gen-ai-spans.md
  docs/general/events.md
  docs/general/logs.md
  docs/general/metrics.md
  docs/general/trace.md
  docs/http/http-metrics.md
  docs/http/http-spans.md
  docs/messaging/messaging-metrics.md
  docs/messaging/messaging-spans.md
  docs/resource/README.md
  docs/rpc/connect-rpc.md
  docs/rpc/grpc.md
  docs/runtime/jvm-metrics.md
  internal/tools/update_specification_version.sh
Labels: Skip Changelog

#1316 [editorial] Fix invalid `#instrument-advice` anchors
  docs/faas/faas-metrics.md
  docs/messaging/messaging-metrics.md
Labels: Skip Changelog

#1310 Stable semconv migration clarification
  docs/database/README.md
  docs/database/database-metrics.md
  docs/database/database-spans.md
  docs/http/README.md
  docs/http/http-metrics.md
  docs/http/http-spans.md
  docs/messaging/messaging-metrics.md
  docs/messaging/messaging-spans.md
  docs/rpc/rpc-metrics.md
  docs/rpc/rpc-spans.md
Labels: Skip Changelog

#1303 [editorial] remove 'full' options from markdown snippets, remove unused tags
  docs/database/cassandra.md
  docs/database/cosmosdb.md
  docs/database/couchdb.md
  docs/database/database-metrics.md
  docs/database/database-spans.md
  docs/database/elasticsearch.md
  docs/database/hbase.md
  docs/database/mongodb.md
  docs/database/mssql.md
  docs/database/redis.md
  docs/database/sql.md
  docs/dns/dns-metrics.md
  docs/dotnet/dotnet-aspnetcore-metrics.md
  docs/dotnet/dotnet-kestrel-metrics.md
  docs/dotnet/dotnet-signalr-metrics.md
  docs/faas/faas-metrics.md
  docs/faas/faas-spans.md
  docs/gen-ai/gen-ai-metrics.md
  docs/general/attributes.md
  docs/general/logs.md
  docs/general/trace-compatibility.md
  docs/graphql/graphql-spans.md
  docs/http/http-metrics.md
  docs/http/http-spans.md
  docs/messaging/gcp-pubsub.md
  docs/messaging/kafka.md
  docs/messaging/messaging-metrics.md
  docs/messaging/messaging-spans.md
  docs/messaging/rabbitmq.md
  docs/messaging/rocketmq.md
  docs/mobile/events.md
  docs/resource/README.md
  docs/resource/cloud-provider/aws/ecs.md
  docs/resource/cloud.md
  docs/resource/host.md
  docs/resource/os.md
  docs/rpc/connect-rpc.md
  docs/rpc/grpc.md
  docs/rpc/json-rpc.md
  docs/rpc/rpc-metrics.md
  docs/rpc/rpc-spans.md
  docs/runtime/go-metrics.md
  docs/runtime/jvm-metrics.md
  docs/runtime/nodejs-metrics.md
  docs/runtime/v8js-metrics.md
  docs/system/container-metrics.md
  docs/system/process-metrics.md
  docs/system/system-metrics.md
  model/registry/messaging.yaml
Labels: Skip Changelog

#1030 move common hardware attributes and metrics to registry
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/change_proposal.yaml
  .github/ISSUE_TEMPLATE/new-conventions.yaml
  docs/attributes-registry/README.md
  docs/attributes-registry/hardware.md
  docs/hardware/README.md
  docs/hardware/common.md
  docs/system/hardware-metrics.md
  model/hardware-common.yaml
  model/metrics/hardware/common.yaml
  model/registry/hardware.yaml
Labels: Skip Changelog, never stale

#1314 Rename veight groups to v8
  docs/runtime/v8js-metrics.md
  model/metrics/v8js-metrics.yaml
Labels: Skip Changelog

#1325 Fix array attribute examples
  docs/attributes-registry/container.md
  docs/attributes-registry/gen-ai.md
  docs/attributes-registry/tls.md
  docs/gen-ai/gen-ai-spans.md
  docs/resource/container.md
  model/registry/aws.yaml
  model/registry/browser.yaml
  model/registry/container.yaml
  model/registry/gen-ai.yaml
  model/registry/host.yaml
  model/registry/messaging.yaml
  model/registry/process.yaml
  model/registry/tls.yaml
  model/registry/user.yaml
Labels: Skip Changelog

#1331 Fix `process.args_count` attribute
  docs/attributes-registry/process.md
  model/registry/process.yaml
Labels: Skip Changelog

#1328 Attempt to optimise attribute name collision checks.
  policies/attribute_name_collisions.rego
Labels: Skip Changelog

#1346 (chore) Add dependabot config to keep tooling up to date.
  .github/dependabot.yml
Labels: Skip Changelog

#1354 Fix link anchors
  docs/attributes-registry/db.md
  docs/general/attributes.md
  docs/messaging/gcp-pubsub.md
  model/registry/db.yaml
  model/trace/messaging.yaml
Labels: Skip Changelog

#1352 chore: update ids
  docs/runtime/nodejs-metrics.md
  model/metrics/nodejs-metrics.yaml
Labels: Skip Changelog

#1347 chore: Keep docker containers up to date with latest patches.
  Makefile
  dependencies.Dockerfile
Labels: Skip Changelog

#1326 Fix yaml schema violations and formatting
  model/messaging-common.yaml
  model/registry/aws.yaml
  model/registry/code.yaml
  model/registry/db.yaml
  model/registry/deployment.yaml
  model/registry/event.yaml
  model/registry/exception.yaml
  model/registry/url.yaml
  model/registry/user-agent.yaml
  model/registry/webengine.yaml
  model/resource/os.yaml
  model/trace/faas.yaml
Labels: Skip Changelog

#1035 Add initial experimental .NET CLR runtime metrics
  .chloggen/clr-runtime.yaml
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/change_proposal.yaml
  .github/ISSUE_TEMPLATE/new-conventions.yaml
  docs/attributes-registry/README.md
  docs/attributes-registry/dotnet.md
  docs/runtime/README.md
  docs/runtime/dotnet-metrics.md
  model/metrics/dotnet-metrics.yaml
  model/registry/dotnet.yaml
  templates/registry/markdown/weaver.yaml
Labels: Stale

#1359 chore: No longer run weaver as root, or give full filesystem access
  Makefile
  dependencies.Dockerfile
Labels: Skip Changelog
