Repository open-telemetry/semantic-conventions, pull requests merged in 2024-11, with the labels that each got.

#1547 Use wikipedia for OSI link instead of osi-model.com
  CHANGELOG.md
  docs/attributes-registry/cicd.md
  docs/attributes-registry/network.md
  docs/attributes-registry/test.md
  docs/attributes-registry/vcs.md
  docs/dotnet/dotnet-kestrel-metrics.md
  docs/general/attributes.md
  docs/http/http-metrics.md
  docs/http/http-spans.md
  docs/rpc/rpc-metrics.md
  docs/rpc/rpc-spans.md
  docs/system/system-metrics.md
  model/cicd/registry.yaml
  model/network/registry.yaml
  model/test/registry.yaml
  model/vcs/registry.yaml
Labels: Skip Changelog

#1553 Remove duplicate
  model/database/spans.yaml
Labels: Skip Changelog

#1562 Use project version of markdown-link-check package
  .github/workflows/changelog.yml
  Makefile
Labels: Skip Changelog

#1563 Forgot `make` in the workflow command
  .github/workflows/changelog.yml
  Makefile
Labels: Skip Changelog

#971 Specific URL query string values should be redacted
  .chloggen/971.yaml
  docs/attributes-registry/url.md
  docs/database/elasticsearch.md
  docs/http/http-spans.md
  docs/url/url.md
  model/url/registry.yaml
Labels: never stale

#1551 Remove "sampling relevant" from metric sections
  docs/database/cosmosdb.md
  docs/database/database-metrics.md
  model/database/common.yaml
Labels: Skip Changelog

#1585 process: change process.uptime instrument to gauge
  .chloggen/process_uptime.yaml
  docs/system/process-metrics.md
  model/process/metrics.yaml
Labels: contribfest

#1584 [chore] Fixed a dead link for machine id man page
  docs/attributes-registry/service.md
  docs/resource/README.md
  model/service/registry.yaml
Labels: Skip Changelog

#1574 Extend GenAI system to support IBM Watsonx AI and AWS Bedrock
  .chloggen/1574.yaml
  docs/attributes-registry/gen-ai.md
  docs/gen-ai/gen-ai-events.md
  docs/gen-ai/gen-ai-metrics.md
  docs/gen-ai/gen-ai-spans.md
  model/gen-ai/registry.yaml
Labels: area:gen-ai

#1116 Add geo fields into attribute registry
  .chloggen/geo_fields.yaml
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/change_proposal.yaml
  .github/ISSUE_TEMPLATE/new-conventions.yaml
  docs/attributes-registry/README.md
  docs/attributes-registry/geo.md
  model/geo/registry.yaml
Labels: never stale

#1586 [chore] Add lightweight make check target
  Makefile
Labels: editorial, tooling, contribfest

#1606 Remove requirement_level usages from registry and add a policy to check
  model/aspnetcore/metrics.yaml
  model/aspnetcore/registry.yaml
  model/aws/registry.yaml
  model/go/registry.yaml
  model/process/registry.yaml
  model/telemetry/registry.yaml
  policies/registry.rego
  policies_test/registry_test.rego
Labels: tooling, Skip Changelog

#1607 Add missing sections and owners to codeowners files
  .github/CODEOWNERS
  docs/feature-flags/feature-flags-logs.md
  model/feature-flags/deprecated/registry-deprecated.yaml
  model/feature-flags/logs.yaml
  model/feature-flags/registry.yaml
Labels: Skip Changelog

#1566 Don't capture `db.operation.name` and `db.collection.name` from query formats that support multiples
  .chloggen/1566.yaml
  docs/attributes-registry/db.md
  docs/database/cassandra.md
  docs/database/cosmosdb.md
  docs/database/database-metrics.md
  docs/database/database-spans.md
  docs/database/hbase.md
  docs/database/mariadb.md
  docs/database/mongodb.md
  docs/database/mssql.md
  docs/database/mysql.md
  docs/database/postgresql.md
  docs/database/redis.md
  docs/database/sql.md
  model/database/common.yaml
  model/database/registry.yaml
  model/database/spans.yaml
Labels: area:db

#1560 Add section on span status for databases
  .chloggen/1560.yaml
  docs/database/database-spans.md
Labels: area:db

#1603 GenAI: define conventions for embeddings operations
  .chloggen/1603.yaml
  CONTRIBUTING.md
  docs/attributes-registry/gen-ai.md
  docs/gen-ai/azure-ai-inference.md
  docs/gen-ai/gen-ai-metrics.md
  docs/gen-ai/gen-ai-spans.md
  docs/gen-ai/openai.md
  model/gen-ai/registry.yaml
  model/gen-ai/spans.yaml
Labels: area:gen-ai

#1619 Add Trask to SemConv maintainers
  README.md
Labels: Skip Changelog
