Repository open-telemetry/semantic-conventions, pull requests merged in 2024-09, with the labels that each got.

#1378 Change deprecated Java example
  docs/general/attributes.md
Labels: Skip Changelog

#1388 ci: sort with dictionary mode for compatibility
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/change_proposal.yaml
  .github/ISSUE_TEMPLATE/new-conventions.yaml
  .github/workflows/scripts/get-registry-areas.sh
Labels: Skip Changelog

#1390 Fix typo in `tls.yaml`
  docs/attributes-registry/tls.md
  model/registry/deprecated/tls.yaml
Labels: Skip Changelog

#1386 ci: fix makefile docker ownership
  Makefile
Labels: Skip Changelog

#1402 Document semconv version weaver is compatible with and update migration docs
  docs/non-normative/code-generation.md
Labels: Skip Changelog

#1329 process: Add build_id to executable
  .chloggen/process-build_id.yaml
  docs/attributes-registry/process.md
  model/registry/process.yaml
Labels: area:cicd

#1171 Give exhaustive specification of span kinds for messaging spans
  .chloggen/1112.yaml
  docs/messaging/messaging-spans.md
Labels: never stale

#1412 Fixed typos in folder names (android and graphql)
  CONTRIBUTING.md
  model/android/deprecated/registry-deprecated.yaml
  model/android/registry.yaml
  model/android/resources.yaml
  model/graphql/registry.yaml
  model/graphql/spans.yml
Labels: Skip Changelog

#1405 Update schema url to the weaver one and replace other links to build-tools
  .vscode/settings.json
  CONTRIBUTING.md
  model/README.md
Labels: tooling, Skip Changelog

#1411 Proposal: Unify metric templates
  docs/database/database-metrics.md
  docs/dns/dns-metrics.md
  docs/dotnet/dotnet-aspnetcore-metrics.md
  docs/dotnet/dotnet-kestrel-metrics.md
  docs/dotnet/dotnet-signalr-metrics.md
  docs/faas/faas-metrics.md
  docs/gen-ai/gen-ai-metrics.md
  docs/hardware/common.md
  docs/http/http-metrics.md
  docs/messaging/messaging-metrics.md
  docs/rpc/rpc-metrics.md
  docs/runtime/dotnet-metrics.md
  docs/runtime/go-metrics.md
  docs/runtime/jvm-metrics.md
  docs/runtime/nodejs-metrics.md
  docs/runtime/v8js-metrics.md
  docs/system/container-metrics.md
  docs/system/k8s-metrics.md
  docs/system/process-metrics.md
  docs/system/system-metrics.md
  templates/registry/markdown/snippet.md.j2
Labels: Skip Changelog

#1418 Fix deprecated note for service bus attributes
  .chloggen/fix-deprecated-messaging-servicebus.yaml
  docs/attributes-registry/messaging.md
  model/messaging/deprecated/registry-deprecated.yaml
Labels: bug, area:messaging

#1414 Add paragraph about usage of parent-child relationship
  .chloggen/messaging-parent-child-trace.yaml
  docs/messaging/messaging-spans.md
Labels: area:messaging

#914 Add remaining ECS attributes for file namespace
  .chloggen/file_leftovers.yaml
  docs/attributes-registry/file.md
  model/file/registry.yaml
Labels: area:security
