Repository open-telemetry/semantic-conventions, pull requests merged in 2025-02, with the labels that each got.

#1848 Make replication controller metrics consistent with resource attributes
  .chloggen/fix_k8s_metrics.yaml
  docs/non-normative/k8s-migration.md
  docs/system/k8s-metrics.md
  model/k8s/deprecated/metrics-deprecated.yaml
  model/k8s/metrics.yaml
  schema-next.yaml
Labels: breaking

#1456 Update enduser domain and add `enduser.pseudo.id`
  .chloggen/add_enduser_pseudo_id.yaml
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/change_proposal.yaml
  docs/attributes-registry/enduser.md
  docs/general/attributes.md
  model/enduser/deprecated/common.yaml
  model/enduser/deprecated/registry-deprecated.yaml
  model/enduser/registry.yaml
Labels: enhancement

#1757 Introduce generic `gen_ai.output.type` instead of `gen_ai.openai.request.response_format`
  .chloggen/1757.yaml
  docs/attributes-registry/gen-ai.md
  docs/gen-ai/azure-ai-inference.md
  docs/gen-ai/gen-ai-spans.md
  docs/gen-ai/openai.md
  model/gen-ai/deprecated/registry-deprecated.yaml
  model/gen-ai/registry.yaml
  model/gen-ai/spans.yaml
Labels: area:gen-ai, breaking

#1860 Delete (basically) empty url README
  docs/url/README.md
Labels: Skip Changelog

#1867 [editorial] Fix invalid links and fragments
  docs/attributes-registry/cloud.md
  docs/attributes-registry/ios.md
  docs/faas/faas-spans.md
  docs/mobile/events.md
  docs/resource/cloud.md
  docs/resource/faas.md
  model/cloud/registry.yaml
  model/device/events.yaml
  model/ios/deprecated/registry-deprecated.yaml
Labels: Skip Changelog

#1882 [editorial] Fix invalid external links with fragments
  docs/attributes-registry/tls.md
  docs/dotnet/dotnet-kestrel-metrics.md
  docs/exceptions/exceptions-spans.md
  model/tls/registry.yaml
Labels: editorial, Skip Changelog

#1881 [editorial] Fix link to example-image-manifest
  docs/attributes-registry/oci.md
  docs/resource/container.md
  model/oci/registry.yaml
Labels: editorial, Skip Changelog

#1890 Set span kind on span definitions or change ambiguous spans to attribute groups
  .chloggen/1889.yaml
  docs/faas/aws-lambda.md
  docs/faas/faas-spans.md
  docs/gen-ai/gen-ai-spans.md
  docs/messaging/messaging-spans.md
  docs/rpc/connect-rpc.md
  docs/rpc/grpc.md
  docs/rpc/json-rpc.md
  model/aws/lambda-spans.yaml
  model/faas/spans.yaml
  model/gen-ai/spans.yaml
  model/messaging/spans.yaml
  model/rpc/spans.yaml
Labels: enhancement, Skip Changelog

#1895 Updating experimental -> development in docs
  CONTRIBUTING.md
  docs/general/semantic-convention-groups.md
  docs/non-normative/code-generation.md
  docs/non-normative/db-migration.md
  docs/runtime/jvm-metrics.md
  docs/runtime/nodejs-metrics.md
  docs/runtime/v8js-metrics.md
  policies_test/group_stability_test.rego
Labels: Skip Changelog

#1631 Add SDK span telemetry metrics
  .chloggen/sdk-span-metrics.yaml
  docs/attributes-registry/otel.md
  docs/general/metrics.md
  docs/otel/sdk-metrics.md
  model/otel/common.yaml
  model/otel/metrics.yaml
  model/otel/registry.yaml
Labels: enhancement, area:otel

#1902 Update to weaver 0.13.2
  .vscode/settings.json
  dependencies.Dockerfile
  docs/gen-ai/gen-ai-agent-spans.md
  model/gen-ai/spans.yaml
  templates/registry/markdown/stability.j2
Labels: Skip Changelog

#1917 [db] rename `db.system` to `db.system.name` for metrics and update values
  .chloggen/rename-db-metric-name.yaml
  docs/database/cassandra.md
  docs/database/couchdb.md
  docs/database/dynamodb.md
  docs/database/elasticsearch.md
  docs/database/hbase.md
  docs/database/mariadb.md
  docs/database/mongodb.md
  docs/database/mssql.md
  docs/database/mysql.md
  docs/database/postgresql.md
Labels: changelog.opentelemetry.io, breaking

#1863 Clarify notes on system-specific databases for operation and collection names
  .chloggen/1863.yaml
  docs/attributes-registry/db.md
  docs/database/cassandra.md
  docs/database/cosmosdb.md
  docs/database/database-metrics.md
  docs/database/database-spans.md
  docs/database/elasticsearch.md
  docs/database/hbase.md
  docs/database/mongodb.md
  docs/database/redis.md
  model/azure/cosmosdb-metrics.yaml
  model/database/common.yaml
  model/database/registry.yaml
  model/database/spans.yaml
Labels: enhancement

#1934 [editorial] Use canonical https URLs
  docs/attributes-registry/url.md
  docs/general/metrics.md
  model/url/registry.yaml
Labels: Skip Changelog

#1939 Revert "Bump go.opentelemetry.io/build-tools/chloggen from 0.18.0 to 0.19.0 in /internal/tools (#1936)"
  internal/tools/go.mod
  internal/tools/go.sum
Labels: Skip Changelog

#1756 Kubernetes: How to populate resource attributes based on attributes, labels and transformation
  .chloggen/k8s-label-recommendations.yaml
  .github/CODEOWNERS
  docs/non-normative/k8s-attributes.md
  docs/resource/k8s.md
Labels: enhancement, area:k8s, changelog.opentelemetry.io

#1737 adjust process.executable.name semantic expectation
  .chloggen/process_executable_name.yaml
  docs/attributes-registry/process.md
  docs/cli/cli-spans.md
  docs/resource/process.md
  model/process/registry.yaml
Labels: enhancement

#1955 Small formatting fix
  docs/code/README.md
Labels: Skip Changelog

#1944 clarify code function name
  .chloggen/1646.yaml
  docs/attributes-registry/code.md
  docs/general/attributes.md
  model/code/registry-deprecated.yaml
  model/code/registry.yaml
Labels: breaking
