Repository open-telemetry/semantic-conventions, pull requests merged in 2025-03, with the labels that each got.

#1896 refactor: move system cpu-related metrics to cpu namespace
  .chloggen/cpu_namespace.yaml
  docs/attributes-registry/cpu.md
  docs/attributes-registry/system.md
  docs/system/README.md
  docs/system/cpu-metrics.md
  docs/system/system-metrics.md
  model/cpu/metrics.yaml
  model/cpu/registry.yaml
  model/system/deprecated/metrics-deprecated.yaml
  model/system/deprecated/registry-deprecated.yaml
  model/system/metrics.yaml
  model/system/registry.yaml
  schema-next.yaml
Labels: breaking

#1922 Define a way to indicate the number of requested response candidates.
  .chloggen/1888.yaml
  docs/attributes-registry/gen-ai.md
  docs/gen-ai/azure-ai-inference.md
  docs/gen-ai/gen-ai-agent-spans.md
  docs/gen-ai/gen-ai-spans.md
  docs/gen-ai/openai.md
  model/gen-ai/registry.yaml
  model/gen-ai/spans.yaml
Labels: enhancement, area:gen-ai

#1599 mark code.* attributes as release candidate
  .chloggen/1599.yaml
  docs/attributes-registry/code.md
  docs/code/README.md
  docs/general/attributes.md
  model/code/common.yaml
  model/code/registry.yaml
Labels: enhancement, changelog.opentelemetry.io

#1958 Update chloggen to 0.20.0
  internal/tools/go.mod
  internal/tools/go.sum
Labels: enhancement, Skip Changelog

#1974 [editorial] Ensure non-norm/k8s-attr page has a title
  docs/non-normative/k8s-attributes.md
Labels: Skip Changelog

#1977 [editorial] Drop page self-link, adjust prose
  docs/non-normative/k8s-attributes.md
Labels: Skip Changelog

#1993 Remove unused old markdown link check
  CHANGELOG.md
  docs/database/database-spans.md
  docs/http/http-spans.md
  docs/messaging/messaging-spans.md
  docs/system/hardware-metrics.md
  docs/system/process-metrics.md
  docs/system/system-metrics.md
  package.json
Labels: Skip Changelog

#2006 Add GCP AppHub resource labels
  .chloggen/gcp-apphub.yaml
  docs/attributes-registry/gcp.md
  docs/resource/cloud-provider/gcp/README.md
  docs/resource/cloud-provider/gcp/apphub.md
  model/gcp/apphub.yaml
  model/gcp/registry.yaml
Labels: enhancement

#2012 [chore] Fix link to apphub api.
  docs/attributes-registry/gcp.md
  docs/resource/cloud-provider/gcp/apphub.md
  model/gcp/registry.yaml
Labels: Skip Changelog

#1997 [vcs] add organization and provider name VCS attributes
  .chloggen/1452-vcs-metrics.yaml
  docs/attributes-registry/vcs.md
  docs/cicd/cicd-metrics.md
  model/vcs/metrics.yaml
  model/vcs/registry.yaml
Labels: enhancement, area:cicd

#2020 [vcs] remove fallback value for vcs provider name attribute
  .chloggen/2020.yaml
  docs/attributes-registry/vcs.md
  docs/cicd/cicd-metrics.md
  model/vcs/registry.yaml
Labels: enhancement, area:cicd

#1923 Add test cases for DB query parsing and sanitization
  docs/non-normative/database-test-cases/db-sql-test-cases.json
Labels: Skip Changelog

#2018 docs/code: show attributes in README
  docs/code/README.md
  docs/general/attributes.md
Labels: Skip Changelog

#2029 Add warning about body fields being moved to complex attributes in the future
  docs/azure/events.md
  docs/feature-flags/feature-flags-logs.md
  docs/gen-ai/gen-ai-events.md
  templates/registry/markdown/event_macros.j2
Labels: Skip Changelog

#1992 Define generic `error.message`
  .chloggen/generic-error.yaml
  docs/attributes-registry/error.md
  model/error/registry.yaml
Labels: enhancement, area:error

#1921 Add SDK Log health metrics
  .chloggen/sdk-log-metrics.yaml
  docs/attributes-registry/otel.md
  docs/otel/sdk-metrics.md
  model/otel/metrics.yaml
  model/otel/registry.yaml
Labels: enhancement

#2033 Normalize spaces in `db.operation.name` (if any)
  .chloggen/2028.yaml
  docs/attributes-registry/db.md
  docs/database/cassandra.md
  docs/database/cosmosdb.md
  docs/database/database-metrics.md
  docs/database/database-spans.md
  model/database/registry.yaml
Labels: enhancement

#2034 `db.operation.parameter.<key>` should not be captured for batch operations
  .chloggen/2034.yaml
  docs/attributes-registry/db.md
  docs/database/cassandra.md
  docs/database/cosmosdb.md
  docs/database/database-spans.md
  docs/database/mariadb.md
  docs/database/mssql.md
  docs/database/mysql.md
  docs/database/postgresql.md
  docs/database/redis.md
  docs/database/sql.md
  model/database/registry.yaml
Labels: enhancement

#2035 Update `db.sql.table` deprecation note
  docs/attributes-registry/db.md
  model/database/deprecated/registry-deprecated.yaml
Labels: Skip Changelog

#2036 Update database migration guide with most recent couple of changes
  docs/non-normative/db-migration.md
Labels: Skip Changelog

#2037 Add `db.stored_procedure.name`
  .chloggen/2037.yaml
  docs/attributes-registry/db.md
  docs/database/cosmosdb.md
  docs/database/database-metrics.md
  docs/database/mariadb.md
  docs/database/mssql.md
  docs/database/mysql.md
  docs/database/postgresql.md
  docs/database/redis.md
  docs/database/sql.md
  docs/non-normative/db-migration.md
  model/database/metrics.yaml
  model/database/registry.yaml
  model/database/spans.yaml
Labels: enhancement
