Repository open-telemetry/semantic-conventions, pull requests merged in 2025-07, with the labels that each got.

#2447 Add copilot instructions for auto-review
  .github/copilot-instructions.md
Labels: Skip Changelog

#2461 Add link to entity modelling guide.
  docs/general/how-to-define-semantic-conventions.md
Labels: Skip Changelog

#2477 Add annotation to exclude collisions on `cloud.platform` enum and add policies
  .chloggen/2477.yaml
  .vscode/settings.json
  dependencies.Dockerfile
  model/cloud/registry.yaml
  policies/registry.rego
  policies_test/registry_test.rego
Labels: area:cloud

#2479 Add the 'deprecated:' attribute to the recently deprecated 'z_os' enum value
  .chloggen/trentm-z_os-enum-value-deprecated-attr.yaml
  docs/registry/attributes/os.md
  docs/registry/entities/os.md
  docs/resource/os.md
  docs/resource/zos.md
  model/os/registry.yaml
Labels: area:os

#2444 Add metric value type everywhere (as code-generation annotation)
  .chloggen/2444.yaml
  model/aspnetcore/metrics.yaml
  model/azure/cosmosdb-metrics.yaml
  model/cicd/metrics.yaml
  model/container/metrics.yaml
  model/cpu/deprecated.yaml
  model/cpython/metrics.yaml
  model/database/deprecated/metrics-deprecated.yaml
  model/database/metrics.yaml
  model/dns/metrics.yaml
  model/dotnet/runtime-metrics.yaml
  model/faas/metrics.yaml
  model/gen-ai/metrics.yaml
  model/go/metrics.yaml
  model/hardware/common-metrics.yaml
  model/hardware/host-metrics.yaml
  model/http/metrics.yaml
  model/jvm/deprecated/metrics-deprecated.yaml
  model/jvm/metrics-experimental.yaml
  model/jvm/metrics.yaml
  model/k8s/deprecated/metrics-deprecated.yaml
  model/k8s/metrics.yaml
  model/kestrel/metrics.yaml
  model/messaging/deprecated/metrics-deprecated.yaml
  model/messaging/metrics.yaml
  model/nodejs/metrics.yaml
  model/otel/deprecated/metrics-deprecated.yaml
  model/otel/metrics.yaml
  model/process/metrics.yaml
  model/rpc/metrics.yaml
  model/signalr/metrics.yaml
  model/system/metrics.yaml
  model/v8js/metrics.yaml
  model/vcs/metrics.yaml
Labels: enhancement

#2046 Update GenAI conventions based on system-specific naming guidance
  .chloggen/gen-ai-system-naming.yaml
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/change_proposal.yaml
  .github/ISSUE_TEMPLATE/new-conventions.yaml
  docs/gen-ai/README.md
  docs/gen-ai/aws-bedrock.md
  docs/gen-ai/azure-ai-inference.md
  docs/gen-ai/gen-ai-agent-spans.md
  docs/gen-ai/gen-ai-events.md
  docs/gen-ai/gen-ai-metrics.md
  docs/gen-ai/gen-ai-spans.md
  docs/gen-ai/openai.md
  docs/registry/attributes/README.md
  docs/registry/attributes/gen-ai.md
  docs/registry/attributes/openai.md
  model/gen-ai/deprecated/registry-deprecated.yaml
  model/gen-ai/events.yaml
  model/gen-ai/metrics.yaml
  model/gen-ai/registry.yaml
  model/gen-ai/spans.yaml
  model/openai/registry.yaml
  schema-next.yaml
  templates/registry/markdown/weaver.yaml
Labels: area:gen-ai, breaking

#2499 Better link checking
  .github/scripts/link-check.sh
  .github/scripts/lychee-config.toml
  .github/workflows/changelog.yml
  .github/workflows/checks.yml
  .github/workflows/daily-link-check.yml
  .github/workflows/reusable-link-check.yml
  .github/workflows/reusable-workflow-notification.yml
  Makefile
Labels: Skip Changelog

#2307 Automate schema-next generation in release workflow
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/prepare-release.yml
  CONTRIBUTING.md
  Makefile
  internal/tools/scripts/generate-schema-next.sh
  internal/tools/scripts/schema-diff/yaml/schema-diff.j2
  internal/tools/scripts/schema-diff/yaml/weaver.yaml
  schema-next.yaml
Labels: Skip Changelog

#2502 Add prototyping requirement for significant changes
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  docs/general/how-to-define-semantic-conventions.md
Labels: editorial, Skip Changelog, docs

#2319 Add k8s Pod volume metrics
  .chloggen/add_k8s_volume_metrics.yaml
  docs/non-normative/k8s-migration.md
  docs/system/k8s-metrics.md
  model/k8s/metrics.yaml
Labels: enhancement, area:k8s

#2232 Attempt a write-up about t-shaped-signals.
  .chloggen/wip-t-shaped-signals.yaml
  docs/general/how-to-define-semantic-conventions.md
  docs/non-normative/how-to-write-conventions/t-shaped-signals.md
Labels: enhancement, area:other

#2489 Add otel.scope.schema_url to non-OTLP exporters
  .chloggen/2489.yaml
  docs/registry/attributes/otel.md
  model/otel/registry.yaml
Labels: enhancement, area:otel

#2540 Enforce consistency of metric briefs
  docs/cicd/cicd-metrics.md
  docs/database/cosmosdb.md
  docs/database/database-metrics.md
  docs/faas/faas-metrics.md
  docs/gen-ai/gen-ai-metrics.md
  docs/hardware/common.md
  docs/hardware/host.md
  docs/otel/sdk-metrics.md
  docs/system/container-metrics.md
  docs/system/k8s-metrics.md
  docs/system/system-metrics.md
  model/azure/cosmosdb-metrics.yaml
  model/container/metrics.yaml
  model/database/metrics.yaml
  model/faas/metrics.yaml
  model/gen-ai/metrics.yaml
  model/hardware/common-metrics.yaml
  model/hardware/host-metrics.yaml
  model/k8s/metrics.yaml
  model/otel/metrics.yaml
  model/system/deprecated/metrics-deprecated.yaml
  model/system/metrics.yaml
  model/vcs/metrics.yaml
  policies/metric_brief_format.rego
  policies_test/metric_brief_format_test.rego
Labels: Skip Changelog

#2526 Add operation name and tool type attributes for Execute tool span.
  .chloggen/2526.yaml
  docs/gen-ai/gen-ai-spans.md
  model/gen-ai/spans.yaml
Labels: enhancement, area:gen-ai

#2542 Add permissions that were missed on the first pass
  .github/workflows/prepare-release.yml
Labels: Skip Changelog
