Repository open-telemetry/semantic-conventions, pull requests merged in 2025-08, with the labels that each got.

#2588 Allow complex attributes on spans
  docs/how-to-write-conventions/README.md
  policies/attribute_types.rego
  policies_test/attribute_types_test.rego
Labels: Skip Changelog

#2596 Update affiliation for lmolkova
  .github/security-insights.yml
  README.md
Labels: Skip Changelog

#2558 [chore] Set enum briefs for Cassandra
  docs/database/cassandra.md
  docs/registry/attributes/cassandra.md
  model/cassandra/registry.yaml
Labels: Stale

#2557 [chore] Set enum briefs for Azure
  docs/database/cosmosdb.md
  docs/registry/attributes/azure.md
  model/azure/registry.yaml
Labels: Stale

#2556 [chore] Set enum briefs for AWS
  docs/registry/attributes/aws.md
  docs/registry/entities/aws.md
  docs/resource/cloud-provider/aws/ecs.md
  model/aws/registry.yaml
Labels: Stale

#2179 Using attributes for chat history on gen_ai spans and events
  .chloggen/2179.yaml
  docs/gen-ai/aws-bedrock.md
  docs/gen-ai/azure-ai-inference.md
  docs/gen-ai/gen-ai-agent-spans.md
  docs/gen-ai/gen-ai-events.md
  docs/gen-ai/gen-ai-input-messages.json
  docs/gen-ai/gen-ai-output-messages.json
  docs/gen-ai/gen-ai-spans.md
  docs/gen-ai/gen-ai-system-instructions.json
  docs/gen-ai/non-normative/examples-llm-calls.md
  docs/gen-ai/non-normative/models.ipynb
  docs/gen-ai/openai.md
  docs/registry/attributes/gen-ai.md
  model/gen-ai/deprecated/events-deprecated.yaml
  model/gen-ai/deprecated/registry-deprecated.yaml
  model/gen-ai/events.yaml
  model/gen-ai/registry.yaml
  model/gen-ai/spans.yaml
  templates/registry/markdown/event_macros.j2
  templates/registry/markdown/examples_macros.j2
Labels: area:gen-ai, breaking

#2508 Add ASP.NET Core identity metrics
  .chloggen/2508.yaml
  docs/dotnet/dotnet-aspnetcore-metrics.md
  docs/registry/attributes/aspnetcore.md
  model/aspnetcore/metrics.yaml
  model/aspnetcore/registry.yaml
Labels: enhancement, area:aspnetcore

#2533 Add ASP.NET Core memory pool metrics
  .chloggen/2532.yaml
  docs/dotnet/dotnet-aspnetcore-metrics.md
  docs/registry/attributes/aspnetcore.md
  model/aspnetcore/metrics.yaml
  model/aspnetcore/registry.yaml
Labels: enhancement, area:aspnetcore

#2531 Add ASP.NET Core AuthN and AuthZ metrics
  .chloggen/2530.yaml
  docs/dotnet/dotnet-aspnetcore-metrics.md
  docs/registry/attributes/aspnetcore.md
  model/aspnetcore/metrics.yaml
  model/aspnetcore/registry.yaml
Labels: enhancement, area:aspnetcore

#2661 Move Johannes Tax to Emeritus Maintainer
  README.md
Labels: Skip Changelog

#2660 Better link text
  docs/registry/attributes/android.md
  docs/registry/attributes/app.md
  docs/registry/attributes/device.md
  docs/registry/entities/android.md
  docs/registry/entities/app.md
  docs/registry/entities/device.md
  docs/resource/android.md
  docs/resource/device.md
  model/android/registry.yaml
  model/app/registry.yaml
  model/device/registry.yaml
Labels: Skip Changelog

#2659 Fix make targets on Windows
  Makefile
Labels: Skip Changelog

#2672 Fix release workflow 3
  internal/tools/scripts/generate-schema-next.sh
Labels: Skip Changelog

#2495 Add SQL commenter as context propagation for databases
  .chloggen/db-context-propagation-via-sql-commenter.yaml
  docs/database/database-spans.md
Labels: enhancement, area:db

#2362 Gen ai.embeddings.dimension.count
  .chloggen/gen_ai_dimension_count.yaml
  docs/gen-ai/gen-ai-spans.md
  docs/registry/attributes/gen-ai.md
  model/gen-ai/registry.yaml
  model/gen-ai/spans.yaml
Labels: enhancement, area:gen-ai

#2683 Small change log formatting
  CHANGELOG.md
Labels: Skip Changelog

#2590 Improve cicd worker description
  .chloggen/1191.yaml
  docs/registry/entities/cicd.md
  docs/resource/cicd.md
  model/cicd/entities.yaml
Labels: enhancement, area:cicd

#2688 Check deprecated.rename_to type compatibility and more
  .chloggen/2688.yaml
  docs/registry/attributes/db.md
  docs/registry/attributes/enduser.md
  docs/registry/attributes/gen-ai.md
  docs/registry/attributes/messaging.md
  model/database/deprecated/registry-deprecated.yaml
  model/enduser/deprecated/registry-deprecated.yaml
  model/gen-ai/deprecated/registry-deprecated.yaml
  model/messaging/deprecated/registry-deprecated.yaml
  policies/deprecation.rego
  policies_test/deprecation_test.rego
Labels: enhancement, area:db, area:messaging, area:enduser

#2691 Fix metrics requirement level link
  docs/hardware/cpu.md
  docs/hardware/disk-controller.md
  docs/hardware/enclosure.md
  docs/hardware/fan.md
  docs/hardware/gpu.md
  docs/hardware/logical-disk.md
  docs/hardware/memory.md
  docs/hardware/network.md
  docs/hardware/physical-disk.md
  docs/hardware/power-supply.md
  docs/hardware/tape-drive.md
  docs/hardware/temperature.md
  docs/hardware/voltage.md
Labels: Skip Changelog
