Repository open-telemetry/semantic-conventions, pull requests merged in 2025-04, with the labels that each got.

#2056 Convert headings to sentence case
  CONTRIBUTING.md
  docs/cloud-providers/aws-sdk.md
  docs/database/database-metrics.md
  docs/database/database-spans.md
  docs/exceptions/exceptions-logs.md
  docs/exceptions/exceptions-spans.md
  docs/faas/aws-lambda.md
  docs/faas/faas-metrics.md
  docs/faas/faas-spans.md
  docs/feature-flags/feature-flags-logs.md
  docs/gen-ai/azure-ai-inference.md
  docs/gen-ai/gen-ai-agent-spans.md
  docs/gen-ai/gen-ai-metrics.md
  docs/gen-ai/openai.md
  docs/general/attributes.md
  docs/general/logs.md
  docs/general/metrics.md
  docs/general/naming.md
  docs/general/semantic-convention-groups.md
  docs/http/http-metrics.md
  docs/messaging/gcp-pubsub.md
  docs/messaging/kafka.md
  docs/non-normative/code-generation.md
  docs/non-normative/compatibility/aws.md
  docs/non-normative/groups/system/design-philosophy.md
  docs/non-normative/groups/system/use-cases.md
  docs/otel/sdk-metrics.md
  docs/resource/README.md
  docs/resource/cloud-provider/aws/README.md
  docs/resource/cloudfoundry.md
  docs/resource/process.md
  docs/rpc/connect-rpc.md
  docs/rpc/rpc-metrics.md
  docs/rpc/rpc-spans.md
  docs/runtime/cpython-metrics.md
  docs/runtime/go-metrics.md
  docs/runtime/jvm-metrics.md
  docs/system/container-metrics.md
  docs/system/cpu-metrics.md
  docs/system/hardware-metrics.md
  docs/system/k8s-metrics.md
  docs/system/process-metrics.md
  docs/system/system-metrics.md
  model/README.md
Labels: Skip Changelog

#1994 Use generic `error.message` in feature flag evaluation event
  .chloggen/ff-generic-error.yaml
  docs/attributes-registry/feature-flag.md
  docs/feature-flags/feature-flags-logs.md
  model/feature-flags/deprecated/registry-deprecated.yaml
  model/feature-flags/events.yaml
  model/feature-flags/registry.yaml
  schema-next.yaml
Labels: breaking

#2066 events: remove uncaught exception example
  docs/general/events.md
Labels: Skip Changelog

#2069 Exclude intersystems.com from link check
  .lychee.toml
Labels: Skip Changelog

#2042 Remove .count suffix from span health metrics
  .chloggen/rename-span-health-metrics.yaml
  docs/otel/sdk-metrics.md
  model/otel/deprecated/metrics-deprecated.yaml
  model/otel/metrics.yaml
  schema-next.yaml
Labels: breaking

#2007 Add http request duration to SDK metrics
  .chloggen/requests-duration.yaml
  docs/otel/sdk-metrics.md
  model/otel/metrics.yaml
Labels: enhancement

#2015 process: Add process.environment_variable.<key>
  .chloggen/attr-env.yaml
  docs/attributes-registry/process.md
  model/process/registry.yaml
Labels: enhancement

#2044 Add security insights file
  .github/security-insights.yml
Labels: Skip Changelog

#2084 Add android codeowners
  .github/CODEOWNERS
Labels: Skip Changelog

#2086 Update weaver to 0.14.0 and allow `_` -> `.` renames
  dependencies.Dockerfile
  docs/dotnet/dotnet-kestrel-metrics.md
  model/kestrel/metrics.yaml
  model/messaging/deprecated/registry-deprecated.yaml
  policies/attribute_name_collisions.rego
  policies_test/attribute_name_collisions_test.rego
Labels: Skip Changelog

#2059 To Add tool description as one of the gen_ai.tool attributes
  .chloggen/2059.yaml
  docs/attributes-registry/gen-ai.md
  docs/gen-ai/gen-ai-spans.md
  model/gen-ai/registry.yaml
  model/gen-ai/spans.yaml
Labels: enhancement

#2095 Add SDK health semconv approvers
  .github/CODEOWNERS
Labels: Skip Changelog

#2097 Add code attribute code owners
  .github/CODEOWNERS
Labels: Skip Changelog

#2093 Add `db.query.parameter.<key>`
  .chloggen/2093.yaml
  docs/attributes-registry/db.md
  docs/database/cassandra.md
  docs/database/cosmosdb.md
  docs/database/database-spans.md
  docs/database/mariadb.md
  docs/database/mssql.md
  docs/database/mysql.md
  docs/database/oracledb.md
  docs/database/postgresql.md
  docs/database/redis.md
  docs/database/sql.md
  model/database/deprecated/registry-deprecated.yaml
  model/database/registry.yaml
  model/database/spans.yaml
Labels: breaking

#1982 Rename `feature_flag.provider_name` to `feature_flag.provider.name`
  .chloggen/feature-flag-provider-name.yaml
  docs/attributes-registry/feature-flag.md
  docs/feature-flags/feature-flags-logs.md
  model/feature-flags/deprecated/registry-deprecated.yaml
  model/feature-flags/events.yaml
  model/feature-flags/registry.yaml
  schema-next.yaml
Labels: breaking

#2049 Add `generate_content` to the list of permissible values for `gen_ai.operation.name`
  .chloggen/generate_content_genai_operation.yaml
  docs/attributes-registry/gen-ai.md
  docs/gen-ai/azure-ai-inference.md
  docs/gen-ai/gen-ai-agent-spans.md
  docs/gen-ai/gen-ai-metrics.md
  docs/gen-ai/gen-ai-spans.md
  docs/gen-ai/openai.md
  model/gen-ai/registry.yaml
Labels: enhancement

#2107 Update yamllint config
  .yamllint
Labels: Skip Changelog

#2090 Pin lychee link checker version
  .lychee.toml
  Makefile
Labels: Skip Changelog

#2106 Update renovate config
  .github/dependabot.yml
  .github/renovate.json5
  renovate.json
Labels: Skip Changelog

#2117 Run checks on merge queue
  .github/workflows/checks.yml
Labels: Skip Changelog

#2121 Fix merge queue
  .github/workflows/changelog.yml
Labels: Skip Changelog

#2050 Propose an update to the values of 'gen_ai.system' for Google.
  .chloggen/gcp_genai_system.yaml
  docs/attributes-registry/gen-ai.md
  docs/gen-ai/gen-ai-agent-spans.md
  docs/gen-ai/gen-ai-events.md
  docs/gen-ai/gen-ai-metrics.md
  docs/gen-ai/gen-ai-spans.md
  model/gen-ai/registry.yaml
Labels: breaking

#2127 Fix merge queue
  .github/workflows/build-system-check.yml
  .github/workflows/changelog.yml
  .github/workflows/checks.yml
  .github/workflows/generate-registry-area-labels.yml
Labels: enhancement, Skip Changelog

#2140 Add ios and client codeowners
  .github/CODEOWNERS
Labels: Skip Changelog

#2130 [k8s] Introduce semantic conventions for k8s Node labels and annotations
  .chloggen/node-labels-annotations.yaml
  docs/attributes-registry/k8s.md
  docs/resource/k8s.md
  model/k8s/registry.yaml
  model/k8s/resources.yaml
Labels: enhancement, area:k8s

#2144 Another merge queue fix
  .github/workflows/changelog.yml
Labels: Skip Changelog

#2139 feat: Add `jvm.file_descriptor.count` metric to jvm experimental metrics
  .chloggen/add-file-descriptor-metric-to-jvm.yaml
  docs/runtime/jvm-metrics.md
  model/jvm/metrics-experimental.yaml
Labels: enhancement

#2122 Separate inference and embeddings spans, remove irrelevant attributes
  .chloggen/1924.yaml
  .chloggen/2122.yaml
  docs/gen-ai/README.md
  docs/gen-ai/azure-ai-inference.md
  docs/gen-ai/gen-ai-agent-spans.md
  docs/gen-ai/gen-ai-spans.md
  docs/gen-ai/openai.md
  model/gen-ai/spans.yaml
Labels: area:gen-ai

#1900 Adding span for invoke agent
  .chloggen/1842.yaml
  docs/gen-ai/gen-ai-agent-spans.md
  model/gen-ai/spans.yaml
Labels: enhancement, area:gen-ai

#2155 Add GC causes to jvm GC related metric
  .chloggen/add-jvm-gc-cause-attribute.yaml
  docs/attributes-registry/jvm.md
  docs/runtime/jvm-metrics.md
  model/jvm/metrics.yaml
  model/jvm/registry.yaml
Labels: enhancement

#2150 Rename file name and internal id from mssql to sql_server
  docs/database/README.md
  docs/database/database-spans.md
  docs/database/sql-server.md
  model/database/spans.yaml
Labels: Skip Changelog

#2151 Use pipe as the `db.namespace` separator
  .chloggen/9999.yaml
  docs/attributes-registry/db.md
  docs/database/cassandra.md
  docs/database/database-metrics.md
  docs/database/database-spans.md
  docs/database/hbase.md
  docs/database/oracledb.md
  docs/database/postgresql.md
  docs/database/sql-server.md
  docs/database/sql.md
  model/database/registry.yaml
  model/database/spans.yaml
Labels: breaking

#2160 Add invoke_agent as a member of gen_ai.operation.name
  .chloggen/2160.yaml
  docs/attributes-registry/gen-ai.md
  docs/gen-ai/azure-ai-inference.md
  docs/gen-ai/gen-ai-agent-spans.md
  docs/gen-ai/gen-ai-metrics.md
  docs/gen-ai/gen-ai-spans.md
  docs/gen-ai/openai.md
  model/gen-ai/registry.yaml
Labels: area:gen-ai

#2181 [k8s] make k8s Node and Pod labels optional
  .chloggen/node-label-opt.yaml
  docs/resource/k8s.md
  model/k8s/resources.yaml
Labels: enhancement, area:k8s, breaking

#2172 [k8s] Introduce semantic conventions for k8s CronJob labels and annotations
  .chloggen/cronjob-labels-annotations.yaml
  docs/attributes-registry/k8s.md
  docs/resource/k8s.md
  model/k8s/registry.yaml
  model/k8s/resources.yaml
Labels: enhancement, area:k8s

#2186 Improve wording of `db.collection.name` and `db.operation.name`
  docs/attributes-registry/db.md
  docs/database/cassandra.md
  docs/database/cosmosdb.md
  docs/database/database-metrics.md
  docs/database/database-spans.md
  model/database/registry.yaml
Labels: Skip Changelog

#2187 Remove outdated sanitization requirement
  docs/attributes-registry/db.md
  docs/database/cassandra.md
  docs/database/cosmosdb.md
  docs/database/database-metrics.md
  docs/database/database-spans.md
  docs/database/elasticsearch.md
  docs/database/mariadb.md
  docs/database/mysql.md
  docs/database/postgresql.md
  docs/database/sql-server.md
  docs/database/sql.md
  model/database/registry.yaml
Labels: Skip Changelog

#2145 Provide guidance on modeling lat/lon, x/y, etc
  .chloggen/2145.yaml
  docs/general/how-to-define-semantic-conventions.md
Labels: enhancement

#2192 Allow entity group type in addition to resource.
  templates/registry/markdown/snippet.md.j2
Labels: Skip Changelog

#2194 Move `db.query.parameter.<key>` from release_candidate back to development
  .chloggen/2194.yaml
  docs/attributes-registry/db.md
  docs/database/cassandra.md
  docs/database/cosmosdb.md
  docs/database/database-spans.md
  docs/database/mariadb.md
  docs/database/mysql.md
  docs/database/oracledb.md
  docs/database/postgresql.md
  docs/database/sql-server.md
  docs/database/sql.md
  model/database/registry.yaml
Labels: enhancement, area:db

#2195 Remove field values from Redis query examples
  docs/database/redis.md
  model/database/spans.yaml
Labels: Skip Changelog

#2171 [k8s] Introduce semantic conventions for k8s Job labels and annotations
  .chloggen/job-labels-annotations.yaml
  docs/attributes-registry/k8s.md
  docs/resource/k8s.md
  model/k8s/registry.yaml
  model/k8s/resources.yaml
Labels: enhancement, area:k8s

#2166 [k8s] Introduce semantic conventions for k8s Namespace labels and annotations
  .chloggen/namespaces-labels-annotations.yaml
  docs/attributes-registry/k8s.md
  docs/resource/k8s.md
  model/k8s/registry.yaml
  model/k8s/resources.yaml
Labels: enhancement, area:k8s

#2170 [k8s] Introduce semantic conventions for k8s DaemonSet labels and annotations
  .chloggen/daemonsets-labels-annotations.yaml
  docs/attributes-registry/k8s.md
  docs/resource/k8s.md
  model/k8s/registry.yaml
  model/k8s/resources.yaml
Labels: enhancement, area:k8s

#2200 Make db.operation.name required where it's available, clarify what to do with multiple layers
  .chloggen/2200.yaml
  docs/database/cosmosdb.md
  docs/database/database-spans.md
  docs/database/hbase.md
  docs/database/mongodb.md
  docs/database/redis.md
  model/database/common.yaml
  model/database/spans.yaml
Labels: enhancement, area:db
