Repository open-telemetry/semantic-conventions, pull requests merged in 2025-05, with the labels that each got.

#2193 Render template attribute name consistently in the table and notes
  docs/attributes-registry/container.md
  docs/attributes-registry/db.md
  docs/attributes-registry/http.md
  docs/attributes-registry/k8s.md
  docs/attributes-registry/process.md
  docs/attributes-registry/rpc.md
  docs/database/cassandra.md
  docs/database/cosmosdb.md
  docs/database/database-spans.md
  docs/database/elasticsearch.md
  docs/database/mariadb.md
  docs/database/mysql.md
  docs/database/oracledb.md
  docs/database/postgresql.md
  docs/database/sql-server.md
  docs/database/sql.md
  docs/http/http-spans.md
  docs/resource/container.md
  docs/resource/k8s.md
  docs/rpc/connect-rpc.md
  docs/rpc/grpc.md
  templates/registry/markdown/attribute_macros.j2
  templates/registry/markdown/attribute_namespace.md.j2
  templates/registry/markdown/attribute_table.j2
Labels: Skip Changelog

#2201 Expand examples of targets in `db.query.summary`
  docs/database/database-spans.md
Labels: Skip Changelog

#2205 Add `db.stored_procedure.name` to the general span conventions
  .chloggen/2205.yaml
  docs/database/cosmosdb.md
  docs/database/database-metrics.md
  docs/database/database-spans.md
  docs/database/mariadb.md
  docs/database/mysql.md
  docs/database/oracledb.md
  docs/database/postgresql.md
  docs/database/redis.md
  docs/database/sql-server.md
  docs/database/sql.md
  model/database/metrics.yaml
  model/database/spans.yaml
Labels: enhancement, area:db

#2207 Add `db.operation.name` and `db.collection.name` to SQL for higher-level APIs
  .chloggen/2207.yaml
  docs/database/mariadb.md
  docs/database/mysql.md
  docs/database/oracledb.md
  docs/database/postgresql.md
  docs/database/sql-server.md
  docs/database/sql.md
  model/database/spans.yaml
Labels: enhancement, area:db

#2070 Introduce app click events
  .chloggen/click_events.yaml
  docs/app/app.md
  docs/attributes-registry/app.md
  model/app/events.yaml
  model/app/registry.yaml
Labels: enhancement

#2212 Remove extra char
  docs/database/database-spans.md
Labels: Skip Changelog

#2206 Add an option to generate db.query.summary from operation/target, restrict its usage for non-query databases
  .chloggen/2206.yaml
  docs/attributes-registry/db.md
  docs/database/cassandra.md
  docs/database/cosmosdb.md
  docs/database/database-metrics.md
  docs/database/database-spans.md
  docs/database/mariadb.md
  docs/database/mysql.md
  docs/database/oracledb.md
  docs/database/postgresql.md
  docs/database/sql-server.md
  docs/database/sql.md
  model/database/common.yaml
  model/database/registry.yaml
  model/database/spans.yaml
Labels: enhancement, area:db

#2211 Make `db.response.returned_rows` opt-in on `release_candidate` spans
  .chloggen/2211.yaml
  docs/database/database-spans.md
  docs/database/mariadb.md
  docs/database/mysql.md
  docs/database/oracledb.md
  docs/database/postgresql.md
  docs/database/sql-server.md
  docs/database/sql.md
  model/database/spans.yaml
Labels: area:db, breaking

#2210 Improve wording of OTEL_SEMCONV_STABILITY_OPT_IN for database semconv
  docs/database/README.md
  docs/database/database-metrics.md
  docs/database/database-spans.md
  docs/non-normative/db-migration.md
Labels: Skip Changelog

#2217 Replace a few remaining `db.system` occurrences with `db.system.name`
  docs/database/database-spans.md
  model/azure/cosmosdb-metrics.yaml
  model/database/common.yaml
  model/database/spans.yaml
Labels: Skip Changelog

#2013 Add CICD spans and resources
  .chloggen/1713-cicd-spans.yaml
  .chloggen/1713-vcs-resources.yaml
  docs/README.md
  docs/attributes-registry/cicd.md
  docs/cicd/README.md
  docs/cicd/cicd-metrics.md
  docs/cicd/cicd-spans.md
  docs/resource/README.md
  docs/resource/cicd.md
  model/cicd/metrics.yaml
  model/cicd/registry.yaml
  model/cicd/resources.yaml
  model/cicd/spans.yaml
  model/vcs/metrics.yaml
  model/vcs/resources.yaml
Labels: area:cicd

#2218 Clarify `db.query.summary` for stored procedures
  .chloggen/2218.yaml
  docs/database/database-spans.md
Labels: area:db

#2199 Mark database semantic conventions as stable for MariaDB, Microsoft SQL Server, MySQL, and PostgreSQL
  .chloggen/2199.yaml
  docs/attributes-registry/db.md
  docs/database/cassandra.md
  docs/database/cosmosdb.md
  docs/database/couchdb.md
  docs/database/database-metrics.md
  docs/database/database-spans.md
  docs/database/elasticsearch.md
  docs/database/hbase.md
  docs/database/mariadb.md
  docs/database/mongodb.md
  docs/database/mysql.md
  docs/database/oracledb.md
  docs/database/postgresql.md
  docs/database/redis.md
  docs/database/sql-server.md
  docs/database/sql.md
  model/database/metrics.yaml
  model/database/registry.yaml
  model/database/spans.yaml
Labels: enhancement, area:db, changelog.opentelemetry.io

#2215 Update DB migration guide
  docs/non-normative/db-migration.md
Labels: Skip Changelog

#2222 Remove warning
  docs/non-normative/db-migration.md
Labels: Skip Changelog

#2230 Updated weaver to v0.15.0
  dependencies.Dockerfile
  docs/attributes-registry/rpc.md
  docs/rpc/connect-rpc.md
  model/http/registry.yaml
  model/rpc/registry.yaml
  policies/entity_association.rego
  policies_test/entity_association_test.rego
Labels: Skip Changelog

#2234 Fix changelog check and update renovate config to stop breaking it
  .github/renovate.json5
  internal/tools/go.sum
Labels: Skip Changelog

#1794 Added new AWS Attributes for various services
  .chloggen/add-new-aws-attributes.yaml
  docs/attributes-registry/aws.md
  docs/attributes-registry/gen-ai.md
  docs/cloud-providers/aws-sdk.md
  docs/faas/aws-lambda.md
  docs/gen-ai/README.md
  docs/gen-ai/aws-bedrock.md
  docs/gen-ai/gen-ai-agent-spans.md
  docs/messaging/README.md
  docs/messaging/sns.md
  docs/messaging/sqs.md
  model/aws/lambda-spans.yaml
  model/aws/registry.yaml
  model/gen-ai/registry.yaml
  model/gen-ai/spans.yaml
  model/messaging/spans.yaml
Labels: enhancement, Skip Changelog, area:aws

#2241 (chore) Remove build-tools from semconv build.
  .github/workflows/checks.yml
  Makefile
  dependencies.Dockerfile
Labels: Skip Changelog

#2163 Add `gen_ai.conversation.id` attribute
  .chloggen/2024.yaml
  docs/attributes-registry/gen-ai.md
  docs/gen-ai/aws-bedrock.md
  docs/gen-ai/azure-ai-inference.md
  docs/gen-ai/gen-ai-agent-spans.md
  docs/gen-ai/gen-ai-spans.md
  docs/gen-ai/openai.md
  model/gen-ai/registry.yaml
  model/gen-ai/spans.yaml
Labels: enhancement, area:gen-ai

#2231 (chore) Move off deprecated group type resource to entity group type.
  docs/resource/cloud-provider/aws/ecs.md
  docs/resource/cloud-provider/aws/eks.md
  docs/resource/cloud-provider/aws/logs.md
  model/android/resources.yaml
  model/app/resources.yaml
  model/aws/ecs-resources.yaml
  model/aws/eks-resources.yaml
  model/aws/logs-resources.yaml
  model/browser/resources.yaml
  model/cicd/resources.yaml
  model/cloud/resources.yaml
  model/cloudfoundry/resources.yaml
  model/container/resources.yaml
  model/deployment/resources.yaml
  model/device/resources.yaml
  model/faas/resources.yaml
  model/gcp/apphub.yaml
  model/gcp/cloud-run-resources.yaml
  model/gcp/gce-resources.yaml
  model/heroku/resources.yaml
  model/host/resources.yaml
  model/k8s/resources.yaml
  model/os/resources.yaml
  model/otel/resources.yaml
  model/process/resources.yaml
  model/service/resources.yaml
  model/telemetry/resources.yaml
  model/vcs/resources.yaml
  model/webengine/resources.yaml
Labels: Skip Changelog

#2244 (chore) Resource -> Entity : Part 2 : Update all group ids, group id guidance and references to group ids.
  .chloggen/2244.yaml
  docs/general/semantic-convention-groups.md
  docs/resource/README.md
  docs/resource/android.md
  docs/resource/browser.md
  docs/resource/cicd.md
  docs/resource/cloud-provider/aws/ecs.md
  docs/resource/cloud-provider/aws/eks.md
  docs/resource/cloud-provider/aws/logs.md
  docs/resource/cloud-provider/gcp/apphub.md
  docs/resource/cloud-provider/gcp/cloud-run.md
  docs/resource/cloud-provider/gcp/gce.md
  docs/resource/cloud-provider/heroku.md
  docs/resource/cloud.md
  docs/resource/cloudfoundry.md
  docs/resource/container.md
  docs/resource/deployment-environment.md
  docs/resource/device.md
  docs/resource/faas.md
  docs/resource/host.md
  docs/resource/k8s.md
  docs/resource/os.md
  docs/resource/process.md
  docs/resource/webengine.md
  model/android/entities.yaml
  model/app/entities.yaml
  model/aws/ecs-entities.yaml
  model/aws/eks-entities.yaml
  model/aws/logs-entities.yaml
  model/browser/entities.yaml
  model/cicd/entities.yaml
  model/cloud/entities.yaml
  model/cloudfoundry/entities.yaml
  model/container/entities.yaml
  model/deployment/entities.yaml
  model/device/entities.yaml
  model/faas/entities.yaml
  model/gcp/apphub.yaml
  model/gcp/cloud-run-entities.yaml
  model/gcp/gce-entities.yaml
  model/heroku/entities.yaml
  model/host/entities.yaml
  model/k8s/entities.yaml
  model/os/entities.yaml
  model/otel/entities.yaml
  model/process/entities.yaml
  model/service/entities.yaml
  model/telemetry/entities.yaml
  model/vcs/entities.yaml
  model/webengine/entities.yaml
  policies/group_stability.rego
Labels: enhancement

#2047 Use deprecated struct instead of text, add policies
  .chloggen/2047.yaml
  .vscode/settings.json
  docs/attributes-registry/android.md
  docs/attributes-registry/code.md
  docs/attributes-registry/container.md
  docs/attributes-registry/db.md
  docs/attributes-registry/deployment.md
  docs/attributes-registry/enduser.md
  docs/attributes-registry/event.md
  docs/attributes-registry/gen-ai.md
  docs/attributes-registry/http.md
  docs/attributes-registry/ios.md
  docs/attributes-registry/messaging.md
  docs/attributes-registry/network.md
  docs/attributes-registry/otel.md
  docs/attributes-registry/process.md
  docs/attributes-registry/system.md
  docs/attributes-registry/vcs.md
  model/android/deprecated/registry-deprecated.yaml
  model/code/registry-deprecated.yaml
  model/container/deprecated/registry-deprecated.yaml
  model/database/deprecated/metrics-deprecated.yaml
  model/database/deprecated/registry-deprecated.yaml
  model/deployment/deprecated/registry-deprecated.yaml
  model/enduser/deprecated/registry-deprecated.yaml
  model/event/deprecated/registry-deprecated.yaml
  model/exceptions/deprecated/registry-deprecated.yaml
  model/feature-flags/deprecated/registry-deprecated.yaml
  model/gen-ai/deprecated/registry-deprecated.yaml
  model/http/deprecated/registry-deprecated.yaml
  model/ios/deprecated/registry-deprecated.yaml
  model/jvm/deprecated/metrics-deprecated.yaml
  model/k8s/deprecated/metrics-deprecated.yaml
  model/k8s/deprecated/registry-deprecated.yaml
  model/messaging/deprecated/metrics-deprecated.yaml
  model/messaging/deprecated/registry-deprecated.yaml
  model/network/deprecated/registry-deprecated.yaml
  model/otel/deprecated/metrics-deprecated.yaml
  model/otel/deprecated/registry-deprecated.yaml
  model/process/deprecated/registry-deprecated.yaml
  model/rpc/deprecated/registry-deprecated.yaml
  model/system/deprecated/metrics-deprecated.yaml
  model/system/deprecated/registry-deprecated.yaml
  model/tls/deprecated/registry-deprecated.yaml
  model/vcs/deprecated/registry-deprecated.yaml
  policies/deprecation.rego
  policies/registry.rego
  policies_test/attribute_name_collisions_test.rego
  policies_test/deprecation_test.rego
  templates/registry/markdown/attribute_namespace.md.j2
  templates/registry/markdown/attribute_table.j2
  templates/registry/markdown/body_field_table.j2
  templates/registry/markdown/enum_macros.j2
  templates/registry/markdown/event_macros.j2
  templates/registry/markdown/metric_table.j2
  templates/registry/markdown/resource_macros.j2
  templates/registry/markdown/stability.j2
Labels: breaking

#1990 Move the evaluated value from the event body to attributes
  .chloggen/ff-value-body-attribute.yaml
  docs/attributes-registry/feature-flag.md
  docs/feature-flags/feature-flags-logs.md
  model/feature-flags/events.yaml
  model/feature-flags/registry.yaml
Labels: breaking

#2238 Expand the intended use of the cloud.region attribute
  .chloggen/cloud-region-attr-modification.yaml
  docs/attributes-registry/cloud.md
  docs/cloud-providers/aws-sdk.md
  docs/database/dynamodb.md
  docs/object-stores/s3.md
  docs/resource/cloud.md
  model/aws/sdk-spans.yaml
  model/cloud/registry.yaml
Labels: enhancement, area:cloud

#2273 Add test for enum member id format
  policies_test/yaml_schema_test.rego
Labels: Skip Changelog

#1708 Add system-specific naming guidance
  .chloggen/1708.yaml
  docs/general/naming.md
Labels: enhancement

#2276 Fix system name for MySQL
  .chloggen/2276.yaml
  docs/database/mysql.md
  model/database/spans.yaml
Labels: area:db

#2279 Remove mentions of build-tools semconvgen
  docs/non-normative/code-generation.md
  model/azure/cosmosdb-metrics.yaml
  model/cpu/registry.yaml
  model/database/common.yaml
  model/database/metrics.yaml
  model/database/spans.yaml
  model/feature-flags/events.yaml
  model/gen-ai/spans.yaml
  model/kestrel/metrics.yaml
  model/messaging/common.yaml
  model/messaging/spans.yaml
Labels: Skip Changelog

#2286 Fix release automation
  .github/workflows/prepare-release.yml
  schema-next.yaml
Labels: Skip Changelog

#2288 Fix link in v1.33.0 change log
  CHANGELOG.md
Labels: Skip Changelog

#2290 Fix ruby links
  docs/exceptions/exceptions-spans.md
Labels: Skip Changelog

#2277 Mark feature flag semantic conventions as release candidate
  .chloggen/ff-logs-rc.yaml
  docs/feature-flags/README.md
  docs/feature-flags/feature-flags-logs.md
  docs/registry/attributes/feature-flag.md
  model/feature-flags/events.yaml
  model/feature-flags/registry.yaml
Labels: enhancement

#2299 Fix typo in http deprecated doc
  docs/registry/attributes/http.md
  model/http/deprecated/registry-deprecated.yaml
Labels: Skip Changelog

#2240 Update general event guidance and policies to allow complex attributes on events only
  .chloggen/complex-attributes-on-events.yaml
  .vscode/settings.json
  docs/general/events.md
  docs/general/how-to-define-semantic-conventions.md
  policies/attribute_types.rego
  policies_test/attribute_types_test.rego
Labels: enhancement

#2178 Add k8s container resource related metrics
  .chloggen/add_k8s_container_metrics.yaml
  docs/non-normative/k8s-migration.md
  docs/system/k8s-metrics.md
  model/k8s/metrics.yaml
Labels: enhancement, area:k8s

#2191 Add k8s.container.restart.count metric
  .chloggen/add_c_restarts.yaml
  docs/non-normative/k8s-migration.md
  docs/system/k8s-metrics.md
  model/k8s/metrics.yaml
Labels: enhancement, area:k8s

#2295 Revert `cpu.*` metrics to `system.cpu.*`
  .chloggen/cpu_time_revert.yaml
  docs/system/README.md
  docs/system/cpu-metrics.md
  docs/system/system-metrics.md
  model/cpu/deprecated.yaml
  model/system/deprecated/metrics-deprecated.yaml
  model/system/metrics.yaml
  schema-next.yaml
Labels: area:system, breaking

#1784 add k8s.container.status.state and k8s.container.status.reason metrics
  .chloggen/container-status.yaml
  docs/registry/attributes/k8s.md
  docs/system/k8s-metrics.md
  model/k8s/metrics.yaml
  model/k8s/registry.yaml
Labels: enhancement, area:k8s

#2197 Add k8s.container.ready metric
  .chloggen/add_k8s_container_ready.yaml
  docs/non-normative/k8s-migration.md
  model/k8s/metrics.yaml
Labels: enhancement, area:k8s

#2308 Add k8s.container.ready to md
  docs/system/k8s-metrics.md
Labels: Skip Changelog
