Repository open-telemetry/semantic-conventions, pull requests merged in 2025-01, with the labels that each got.

#1706 Update markdownlint
  .github/workflows/checks.yml
  Makefile
  gulpfile.js
  package.json
Labels: Skip Changelog

#1718 Upgrade rego to v1
  dependencies.Dockerfile
  policies/group_stability.rego
  policies/registry.rego
  policies/yaml_schema.rego
  policies_test/yaml_schema_test.rego
Labels: Skip Changelog

#1724 Fix lychee toml config
  .lychee.toml
  docs/general/naming.md
  docs/hardware/README.md
  docs/runtime/README.md
  docs/system/hardware-metrics.md
  docs/system/process-metrics.md
  docs/system/system-metrics.md
Labels: Skip Changelog

#1723 Use lychee for changelog links
  .github/workflows/changelog.yml
  .lychee.toml
  Makefile
Labels: Skip Changelog

#1725 Update codeowners: use weaver-approvers group
  .github/CODEOWNERS
Labels: Skip Changelog

#1660 Add k8s metrics for jobs and cronjobs
  .chloggen/add_k8s_jobs.yaml
  docs/non-normative/k8s-migration.md
  docs/system/k8s-metrics.md
  model/k8s/metrics.yaml
Labels: area:k8s

#1727 Update http-spans.md example POST
  docs/http/http-spans.md
Labels: Skip Changelog

#1730 Messaging: Align span kind in example tables with the spec
  docs/messaging/messaging-spans.md
Labels: Skip Changelog, area:messaging

#1618 [chore] System Semantic Conventions Non-Normative Guidance
  .github/CODEOWNERS
  .prettierignore
  docs/non-normative/groups/system/design-philosophy.md
  docs/non-normative/groups/system/use-cases.md
  package.json
Labels: Skip Changelog, area:system

#1738 Add profiling approvers to CODEOWNERS
  .github/CODEOWNERS
Labels: Skip Changelog

#1531 RabbitMQ: Specify how to populate `messaging.destination.name`
  .chloggen/rabbitmq-destination-name.yaml
  docs/messaging/rabbitmq.md
  model/messaging/spans.yaml
Labels: area:messaging

#1745 Fix small typos
  docs/database/README.md
  docs/database/database-metrics.md
  docs/database/database-spans.md
Labels: Skip Changelog

#1750 [chore] updated changelog for gen-ai
  .chloggen/1655.yaml
  .chloggen/1719.yaml
Labels: Skip Changelog

#1754 [chore] Added content for update toc
  CONTRIBUTING.md
Labels: docs

#1753 [editorial] Adjust link into in-toto attestation spec
  docs/attributes-registry/artifact.md
  model/artifact/registry.yaml
Labels: editorial, Skip Changelog

#1763 Update specification version to 1.40.0
  README.md
  docs/database/cosmosdb.md
  docs/database/database-metrics.md
  docs/database/database-spans.md
  docs/dns/dns-metrics.md
  docs/dotnet/dotnet-aspnetcore-metrics.md
  docs/dotnet/dotnet-dns-metrics.md
  docs/dotnet/dotnet-http-metrics.md
  docs/dotnet/dotnet-kestrel-metrics.md
  docs/dotnet/dotnet-signalr-metrics.md
  docs/exceptions/exceptions-logs.md
  docs/faas/aws-lambda.md
  docs/faas/faas-metrics.md
  docs/feature-flags/feature-flags-logs.md
  docs/gen-ai/gen-ai-metrics.md
  docs/gen-ai/gen-ai-spans.md
  docs/general/events.md
  docs/general/logs.md
  docs/general/metrics.md
  docs/general/recording-errors.md
  docs/general/trace.md
  docs/http/http-metrics.md
  docs/http/http-spans.md
  docs/messaging/messaging-metrics.md
  docs/messaging/messaging-spans.md
  docs/resource/README.md
  docs/resource/cloudfoundry.md
  docs/rpc/connect-rpc.md
  docs/rpc/grpc.md
  docs/runtime/jvm-metrics.md
  docs/runtime/nodejs-metrics.md
  docs/runtime/v8js-metrics.md
  internal/tools/update_specification_version.sh
Labels: Skip Changelog

#1766 Fix website linking
  docs/general/naming.md
Labels: Skip Changelog

#1758 Add clarification about `OTEL_SEMCONV_STABILITY_OPT_IN`
  docs/non-normative/db-migration.md
  docs/non-normative/http-migration.md
Labels: Skip Changelog

#1761 Fix link
  docs/general/recording-errors.md
Labels: Skip Changelog

#1762 Move release instructions to RELEASING.md
  CONTRIBUTING.md
  RELEASING.md
Labels: Skip Changelog

#1765 Release automation
  .github/workflows/prepare-release.yml
  .github/workflows/scripts/use-cla-approved-github-bot.sh
Labels: Skip Changelog

#1767 Label all new issues with `triage:needs-triage` label
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/change_proposal.yaml
  .github/ISSUE_TEMPLATE/new-conventions.yaml
  .github/workflows/scripts/prepare-new-issue.sh
Labels: Skip Changelog

#1668 Add k8s.namespace.phase metric and attribute
  .chloggen/add_k8s_ns_phase.yaml
  docs/attributes-registry/k8s.md
  docs/non-normative/k8s-migration.md
  docs/system/k8s-metrics.md
  model/k8s/metrics.yaml
  model/k8s/registry.yaml
Labels: area:k8s

#1771 Update issue templates (simplify and clarify the process)
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/change_proposal.yaml
  .github/ISSUE_TEMPLATE/new-conventions.yaml
Labels: Skip Changelog

#1785 Add warning to db migration guide
  docs/non-normative/db-migration.md
Labels: editorial, Skip Changelog

#1778 Update release instructions
  RELEASING.md
Labels: Skip Changelog

#1764 Don't render deprecated enum members
  docs/attributes-registry/db.md
  docs/attributes-registry/messaging.md
  docs/attributes-registry/system.md
  templates/registry/markdown/enum_macros.j2
Labels: Skip Changelog

#1769 Label PRs that contain breaking changes based on the changelog
  .github/workflows/prepare-new-issue.yml
  .github/workflows/prepare-new-pr.yml
  .github/workflows/scripts/prepare-new-pr.sh
Labels: Skip Changelog

#1786 Temporarily ignore failing link
  .lychee.toml
Labels: Skip Changelog

#1788 Fix broken link to redis HMSET command
  docs/database/redis.md
  model/database/spans.yaml
Labels: Skip Changelog

#1787 Fix PR CI check: specify forked repo
  .github/workflows/prepare-new-pr.yml
Labels: Skip Changelog

#1781 Add stability to `network.interface.name` and event fields, add temp policy check
  model/device/events.yaml
  model/gen-ai/events.yaml
  model/network/registry.yaml
  policies/registry.rego
  policies_test/registry_test.rego
  policies_test/yaml_schema_test.rego
  templates/registry/markdown/stability.j2
Labels: Skip Changelog

#1780 Add note about logical and physical cpu numbers calculation
  .chloggen/improve_cpu_brief.yaml
  docs/system/system-metrics.md
  model/system/metrics.yaml
Labels: enhancement

#1735 model/profile: add frame.type for Erlang
  .chloggen/profile-frame-type-beam.yaml
  docs/attributes-registry/profile.md
  docs/general/profiles.md
  model/profile/registry.yaml
Labels: enhancement

#1681 Add CICD metrics
  .chloggen/1600-cicd-metrics.yaml
  .vscode/settings.json
  docs/attributes-registry/cicd.md
  docs/cicd/cicd-metrics.md
  model/cicd/metrics.yaml
  model/cicd/registry.yaml
Labels: enhancement

#1801 Fix TOC
  docs/exceptions/exceptions-spans.md
Labels: Skip Changelog

#1805 [editorial] Fix alias in general/trace.md
  docs/general/trace.md
Labels: Skip Changelog

#1685 [vcs] add `vcs.change.time_to_merge` metric
  .chloggen/vcs-ttm.yaml
  docs/attributes-registry/vcs.md
  docs/cicd/cicd-metrics.md
  model/vcs/metrics.yaml
  model/vcs/registry.yaml
Labels: enhancement

#1779 Database: mention metrics in system-specific docs
  .chloggen/1779.yaml
  docs/database/cassandra.md
  docs/database/cosmosdb.md
  docs/database/couchdb.md
  docs/database/database-spans.md
  docs/database/dynamodb.md
  docs/database/elasticsearch.md
  docs/database/hbase.md
  docs/database/mariadb.md
  docs/database/mongodb.md
  docs/database/mssql.md
  docs/database/mysql.md
  docs/database/postgresql.md
Labels: enhancement

#1772 Update `process.runtime` example for the Python language
  .chloggen/1772.yaml
  docs/resource/process.md
Labels: enhancement

#1734 Consistent naming: `db.system` to `db.system.name`, namespace constants, remove `db` from system-specific names
  .chloggen/1734.yaml
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/change_proposal.yaml
  docs/attributes-registry/README.md
  docs/attributes-registry/aws.md
  docs/attributes-registry/azure.md
  docs/attributes-registry/cassandra.md
  docs/attributes-registry/db.md
  docs/attributes-registry/elasticsearch.md
  docs/database/README.md
  docs/database/cassandra.md
  docs/database/cosmosdb.md
  docs/database/couchdb.md
  docs/database/database-metrics.md
  docs/database/database-spans.md
  docs/database/dynamodb.md
  docs/database/elasticsearch.md
  docs/database/hbase.md
  docs/database/mariadb.md
  docs/database/mongodb.md
  docs/database/mssql.md
  docs/database/mysql.md
  docs/database/postgresql.md
  docs/database/redis.md
  docs/database/sql.md
  docs/general/attribute-requirement-level.md
  internal/tools/scripts/registry/areas.md.j2
  model/aws/registry.yaml
  model/azure/cosmosdb-metrics.yaml
  model/azure/registry.yaml
  model/cassandra/registry.yaml
  model/database/common.yaml
  model/database/deprecated/metrics-deprecated.yaml
  model/database/deprecated/registry-deprecated.yaml
  model/database/metrics.yaml
  model/database/registry.yaml
  model/database/spans.yaml
  model/elasticsearch/registry.yaml
  schema-next.yaml
Labels: area:db, breaking

#1793 Less release steps
  .github/scripts/prepare-new-issue.sh
  .github/scripts/prepare-new-pr.sh
  .github/scripts/update-spec-repo-links.sh
  .github/scripts/use-cla-approved-github-bot.sh
  .github/workflows/auto-update-spec-repo-links.yml
  .github/workflows/prepare-new-issue.yml
  .github/workflows/prepare-new-pr.yml
  .github/workflows/prepare-release.yml
  CONTRIBUTING.md
  RELEASING.md
Labels: tooling, Skip Changelog

#1816 [editorial] Set alias of semantic-convention-groups.md to group-stabi…
  docs/general/semantic-convention-groups.md
Labels: Skip Changelog

#1818 [infra] mardown-lint: report missing tocstop
  Makefile
Labels: Skip Changelog

#1810 Update schema_url in prepare release workflow
  .github/workflows/prepare-release.yml
Labels: Skip Changelog

#1814 Fix links
  docs/exceptions/exceptions-logs.md
  docs/gen-ai/gen-ai-events.md
  docs/general/events.md
Labels: Skip Changelog

#1822 [CI] Run auto-update script only under otel org
  .github/workflows/auto-update-spec-repo-links.yml
Labels: Skip Changelog

#1825 [chore] Fix broken SQL Where Wikipedia link
  docs/database/database-spans.md
Labels: area:db

#1811 Add missing release step
  RELEASING.md
Labels: Skip Changelog

#1836 [chore] Fix span kind in kafka example
  docs/messaging/kafka.md
Labels: Skip Changelog, area:messaging

#1831 Fix auto-update spec link workflow
  .github/workflows/auto-update-spec-repo-links.yml
Labels: Skip Changelog

#1847 [editorial] Drop markdown-toc comment from .md files
  docs/cicd/cicd-metrics.md
  docs/database/cosmosdb.md
  docs/database/database-metrics.md
  docs/database/database-spans.md
  docs/dns/dns-metrics.md
  docs/faas/aws-lambda.md
  docs/faas/faas-metrics.md
  docs/faas/faas-spans.md
  docs/gen-ai/gen-ai-events.md
  docs/gen-ai/gen-ai-metrics.md
  docs/gen-ai/gen-ai-spans.md
  docs/gen-ai/openai.md
  docs/general/attributes.md
  docs/general/logs.md
  docs/general/trace-compatibility.md
  docs/http/http-spans.md
  docs/messaging/messaging-metrics.md
  docs/messaging/messaging-spans.md
  docs/resource/README.md
  docs/resource/process.md
  docs/rpc/rpc-metrics.md
  docs/rpc/rpc-spans.md
  docs/runtime/README.md
  docs/runtime/dotnet-metrics.md
  docs/runtime/go-metrics.md
  docs/runtime/jvm-metrics.md
  docs/runtime/nodejs-metrics.md
  docs/runtime/v8js-metrics.md
  docs/system/k8s-metrics.md
  docs/system/process-metrics.md
  docs/system/system-metrics.md
Labels: Skip Changelog

#1846 [editorial] Drop path_base_for_github_subdir from front matter
  docs/README.md
  docs/attributes-registry/README.md
  docs/azure/README.md
  docs/cloud-providers/README.md
  docs/cloudevents/README.md
  docs/code/README.md
  docs/database/README.md
  docs/dotnet/README.md
  docs/exceptions/README.md
  docs/faas/README.md
  docs/feature-flags/README.md
  docs/gen-ai/README.md
  docs/general/README.md
  docs/hardware/README.md
  docs/http/README.md
  docs/messaging/README.md
  docs/mobile/README.md
  docs/non-normative/README.md
  docs/non-normative/compatibility/README.md
  docs/object-stores/README.md
  docs/resource/README.md
  docs/resource/cloud-provider/README.md
  docs/resource/cloud-provider/aws/README.md
  docs/resource/cloud-provider/gcp/README.md
  docs/rpc/README.md
  docs/runtime/README.md
  docs/system/README.md
  docs/url/README.md
  templates/registry/markdown/readme.md.j2
Labels: Skip Changelog

#1742 Add hpa, resource_quota, replication_controller k8s attributes
  .chloggen/add_k8s_resources.yaml
  docs/attributes-registry/k8s.md
  docs/resource/k8s.md
  docs/system/k8s-metrics.md
  model/k8s/metrics.yaml
  model/k8s/registry.yaml
  model/k8s/resources.yaml
Labels: enhancement

#1844 [CI] Report non-normalized link from docs into docs
  Makefile
Labels: Skip Changelog

#1845 Yamlize existing session events
  .chloggen/yamlize_session_events_1845.yaml
  docs/general/session.md
  model/session/events.yaml
Labels: breaking

#1434 add User-agent OS attributes
  .chloggen/user_agent_os.yaml
  docs/attributes-registry/user-agent.md
  model/user-agent/registry.yaml
Labels: enhancement, area:user-agent

#1707 First stab at documenting the art of defining semantic conventions
  CONTRIBUTING.md
  docs/general/how-to-define-semantic-conventions.md
Labels: Skip Changelog, docs

#1833 [cicd] add cicd.pipeline.run.url.full attribute
  .chloggen/update-pipeline-url-attributes.yaml
  docs/attributes-registry/cicd.md
  model/cicd/registry.yaml
Labels: enhancement
